### ISSUE TITLE
Problem with running the code

### ISSUE THREAD

**Issue by hcjghr** [resindraburiza/DenseSfMwithKeypointRelocalization#1]
Hi @resindraburiza,

I tried to run the code but I'm getting stuck in the first step: Running setup.m

When I run it I get an error:

 Error in setup (line 8)
run([start_path '/matconvnet_aristoteles/matlab/vl_setupnn']);

The matconvnet_aristoteles, relja_matlab and netvlad are all empty folders. I hope I didnt overlook something obvious but any help would be great!

Thanks

**Comment by resindraburiza** [comment]
@hcjghr 
Hi! thanks for contacting me. For the matconvnet, you have to download it first from here:
http://www.vlfeat.org/matconvnet/
and then put all the downloaded files in the same directory, e.g., matconvnet_new (aristoteles is just the name of my machine actually). 

Then you need to change the path in setup.m to the new matconvnet folder.
